# 配置内置Tomcat启动端口
server:
  port: 8080
# 配置项目名
spring:
  application:
    name: xmall
# 设定转发前后缀
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    favicon:
      enabled: false
# 配置数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmall?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
# 配置JPA相关信息
  jpa:
    show-sql: true
    open-in-view: true
